---
- name: upgrade all packages
  yum: name=* state=latest
  when: ansible_pkg_mgr == 'yum'


- name: upgrade all packages
  apt: update_cache=yes upgrade=dist force=yes
  when: ansible_pkg_mgr == 'apt'

- name: delete unnecessary packages
  apt: autoremove=yes update_cache=no
  # ToDo: For now, it's a bug with emtpy autoremove output
  ignore_errors: true  
  when: ansible_pkg_mgr == 'apt'
